CREATE TABLE IF NOT EXISTS LifeLessons (
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    Code TEXT NOT NULL UNIQUE,
    Title TEXT NOT NULL,
    Summary TEXT NOT NULL,
    Goal TEXT NOT NULL DEFAULT '',
    Explanation TEXT NOT NULL DEFAULT '',
    Consequences TEXT NOT NULL DEFAULT '',
    AgeRange TEXT NOT NULL DEFAULT '',
    Method TEXT NOT NULL DEFAULT '',
    SeekHelp TEXT NOT NULL DEFAULT '',
    KeyPoint TEXT NOT NULL DEFAULT '',
    Content TEXT NOT NULL,
    SortOrder INTEGER NOT NULL DEFAULT 0,
    IsActive INTEGER NOT NULL DEFAULT 1
);
