ALTER TABLE TestCategories ADD COLUMN ParentId INTEGER NULL;
ALTER TABLE TestCategories ADD COLUMN CatalogType TEXT NOT NULL DEFAULT 'tests';
ALTER TABLE LifeLessons ADD COLUMN TopicId INTEGER NOT NULL DEFAULT 0;
